// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/tick.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataStreamService_GetLatestTick_FullMethodName = "/datastream.v1.DataStreamService/GetLatestTick"
	DataStreamService_GetTickRange_FullMethodName  = "/datastream.v1.DataStreamService/GetTickRange"
	DataStreamService_Subscribe_FullMethodName     = "/datastream.v1.DataStreamService/Subscribe"
)

// DataStreamServiceClient is the client API for DataStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataStreamServiceClient interface {
	// Fetch the most recent tick for a symbol
	GetLatestTick(ctx context.Context, in *GetLatestTickRequest, opts ...grpc.CallOption) (*Tick, error)
	// Fetch historical data
	GetTickRange(ctx context.Context, in *GetTickRangeRequest, opts ...grpc.CallOption) (*TickRange, error)
	// Server-side streaming for real-time updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tick], error)
}

type dataStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataStreamServiceClient(cc grpc.ClientConnInterface) DataStreamServiceClient {
	return &dataStreamServiceClient{cc}
}

func (c *dataStreamServiceClient) GetLatestTick(ctx context.Context, in *GetLatestTickRequest, opts ...grpc.CallOption) (*Tick, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tick)
	err := c.cc.Invoke(ctx, DataStreamService_GetLatestTick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStreamServiceClient) GetTickRange(ctx context.Context, in *GetTickRangeRequest, opts ...grpc.CallOption) (*TickRange, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TickRange)
	err := c.cc.Invoke(ctx, DataStreamService_GetTickRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStreamServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataStreamService_ServiceDesc.Streams[0], DataStreamService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Tick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStreamService_SubscribeClient = grpc.ServerStreamingClient[Tick]

// DataStreamServiceServer is the server API for DataStreamService service.
// All implementations must embed UnimplementedDataStreamServiceServer
// for forward compatibility.
type DataStreamServiceServer interface {
	// Fetch the most recent tick for a symbol
	GetLatestTick(context.Context, *GetLatestTickRequest) (*Tick, error)
	// Fetch historical data
	GetTickRange(context.Context, *GetTickRangeRequest) (*TickRange, error)
	// Server-side streaming for real-time updates
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Tick]) error
	mustEmbedUnimplementedDataStreamServiceServer()
}

// UnimplementedDataStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataStreamServiceServer struct{}

func (UnimplementedDataStreamServiceServer) GetLatestTick(context.Context, *GetLatestTickRequest) (*Tick, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestTick not implemented")
}
func (UnimplementedDataStreamServiceServer) GetTickRange(context.Context, *GetTickRangeRequest) (*TickRange, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTickRange not implemented")
}
func (UnimplementedDataStreamServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Tick]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedDataStreamServiceServer) mustEmbedUnimplementedDataStreamServiceServer() {}
func (UnimplementedDataStreamServiceServer) testEmbeddedByValue()                           {}

// UnsafeDataStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataStreamServiceServer will
// result in compilation errors.
type UnsafeDataStreamServiceServer interface {
	mustEmbedUnimplementedDataStreamServiceServer()
}

func RegisterDataStreamServiceServer(s grpc.ServiceRegistrar, srv DataStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedDataStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataStreamService_ServiceDesc, srv)
}

func _DataStreamService_GetLatestTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestTickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStreamServiceServer).GetLatestTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStreamService_GetLatestTick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStreamServiceServer).GetLatestTick(ctx, req.(*GetLatestTickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStreamService_GetTickRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStreamServiceServer).GetTickRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStreamService_GetTickRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStreamServiceServer).GetTickRange(ctx, req.(*GetTickRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStreamService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataStreamServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Tick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStreamService_SubscribeServer = grpc.ServerStreamingServer[Tick]

// DataStreamService_ServiceDesc is the grpc.ServiceDesc for DataStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datastream.v1.DataStreamService",
	HandlerType: (*DataStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestTick",
			Handler:    _DataStreamService_GetLatestTick_Handler,
		},
		{
			MethodName: "GetTickRange",
			Handler:    _DataStreamService_GetTickRange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _DataStreamService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/tick.proto",
}
