// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/tick.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLatestTickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestTickRequest) Reset() {
	*x = GetLatestTickRequest{}
	mi := &file_proto_tick_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestTickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestTickRequest) ProtoMessage() {}

func (x *GetLatestTickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tick_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestTickRequest.ProtoReflect.Descriptor instead.
func (*GetLatestTickRequest) Descriptor() ([]byte, []int) {
	return file_proto_tick_proto_rawDescGZIP(), []int{0}
}

func (x *GetLatestTickRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetTickRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StartTimeMs   int64                  `protobuf:"varint,2,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs     int64                  `protobuf:"varint,3,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickRangeRequest) Reset() {
	*x = GetTickRangeRequest{}
	mi := &file_proto_tick_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickRangeRequest) ProtoMessage() {}

func (x *GetTickRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tick_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickRangeRequest.ProtoReflect.Descriptor instead.
func (*GetTickRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_tick_proto_rawDescGZIP(), []int{1}
}

func (x *GetTickRangeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTickRangeRequest) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *GetTickRangeRequest) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_tick_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tick_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_tick_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type Tick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Open          float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
	Volume        int64                  `protobuf:"varint,8,opt,name=volume,proto3" json:"volume,omitempty"`
	Vwap          float64                `protobuf:"fixed64,9,opt,name=vwap,proto3" json:"vwap,omitempty"`
	TickCount     int32                  `protobuf:"varint,10,opt,name=tick_count,json=tickCount,proto3" json:"tick_count,omitempty"`
	DataSource    string                 `protobuf:"bytes,11,opt,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
	ReceivedAtMs  int64                  `protobuf:"varint,12,opt,name=received_at_ms,json=receivedAtMs,proto3" json:"received_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_proto_tick_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tick_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_proto_tick_proto_rawDescGZIP(), []int{3}
}

func (x *Tick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Tick) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Tick) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Tick) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Tick) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Tick) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Tick) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Tick) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Tick) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *Tick) GetTickCount() int32 {
	if x != nil {
		return x.TickCount
	}
	return 0
}

func (x *Tick) GetDataSource() string {
	if x != nil {
		return x.DataSource
	}
	return ""
}

func (x *Tick) GetReceivedAtMs() int64 {
	if x != nil {
		return x.ReceivedAtMs
	}
	return 0
}

type TickRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticks         []*Tick                `protobuf:"bytes,1,rep,name=ticks,proto3" json:"ticks,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickRange) Reset() {
	*x = TickRange{}
	mi := &file_proto_tick_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickRange) ProtoMessage() {}

func (x *TickRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tick_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickRange.ProtoReflect.Descriptor instead.
func (*TickRange) Descriptor() ([]byte, []int) {
	return file_proto_tick_proto_rawDescGZIP(), []int{4}
}

func (x *TickRange) GetTicks() []*Tick {
	if x != nil {
		return x.Ticks
	}
	return nil
}

func (x *TickRange) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TickRange) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TickRange) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_proto_tick_proto protoreflect.FileDescriptor

const file_proto_tick_proto_rawDesc = "" +
	"\n" +
	"\x10proto/tick.proto\x12\rdatastream.v1\".\n" +
	"\x14GetLatestTickRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"q\n" +
	"\x13GetTickRangeRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\"\n" +
	"\rstart_time_ms\x18\x02 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x03 \x01(\x03R\tendTimeMs\",\n" +
	"\x10SubscribeRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\xbf\x02\n" +
	"\x04Tick\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\b \x01(\x03R\x06volume\x12\x12\n" +
	"\x04vwap\x18\t \x01(\x01R\x04vwap\x12\x1d\n" +
	"\n" +
	"tick_count\x18\n" +
	" \x01(\x05R\ttickCount\x12\x1f\n" +
	"\vdata_source\x18\v \x01(\tR\n" +
	"dataSource\x12$\n" +
	"\x0ereceived_at_ms\x18\f \x01(\x03R\freceivedAtMs\"\x88\x01\n" +
	"\tTickRange\x12)\n" +
	"\x05ticks\x18\x01 \x03(\v2\x13.datastream.v1.TickR\x05ticks\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime2\xf7\x01\n" +
	"\x11DataStreamService\x12K\n" +
	"\rGetLatestTick\x12#.datastream.v1.GetLatestTickRequest\x1a\x13.datastream.v1.Tick\"\x00\x12N\n" +
	"\fGetTickRange\x12\".datastream.v1.GetTickRangeRequest\x1a\x18.datastream.v1.TickRange\"\x00\x12E\n" +
	"\tSubscribe\x12\x1f.datastream.v1.SubscribeRequest\x1a\x13.datastream.v1.Tick\"\x000\x01B'Z%github.com/malharrrr/datastream/protob\x06proto3"

var (
	file_proto_tick_proto_rawDescOnce sync.Once
	file_proto_tick_proto_rawDescData []byte
)

func file_proto_tick_proto_rawDescGZIP() []byte {
	file_proto_tick_proto_rawDescOnce.Do(func() {
		file_proto_tick_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tick_proto_rawDesc), len(file_proto_tick_proto_rawDesc)))
	})
	return file_proto_tick_proto_rawDescData
}

var file_proto_tick_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tick_proto_goTypes = []any{
	(*GetLatestTickRequest)(nil), // 0: datastream.v1.GetLatestTickRequest
	(*GetTickRangeRequest)(nil),  // 1: datastream.v1.GetTickRangeRequest
	(*SubscribeRequest)(nil),     // 2: datastream.v1.SubscribeRequest
	(*Tick)(nil),                 // 3: datastream.v1.Tick
	(*TickRange)(nil),            // 4: datastream.v1.TickRange
}
var file_proto_tick_proto_depIdxs = []int32{
	3, // 0: datastream.v1.TickRange.ticks:type_name -> datastream.v1.Tick
	0, // 1: datastream.v1.DataStreamService.GetLatestTick:input_type -> datastream.v1.GetLatestTickRequest
	1, // 2: datastream.v1.DataStreamService.GetTickRange:input_type -> datastream.v1.GetTickRangeRequest
	2, // 3: datastream.v1.DataStreamService.Subscribe:input_type -> datastream.v1.SubscribeRequest
	3, // 4: datastream.v1.DataStreamService.GetLatestTick:output_type -> datastream.v1.Tick
	4, // 5: datastream.v1.DataStreamService.GetTickRange:output_type -> datastream.v1.TickRange
	3, // 6: datastream.v1.DataStreamService.Subscribe:output_type -> datastream.v1.Tick
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tick_proto_init() }
func file_proto_tick_proto_init() {
	if File_proto_tick_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tick_proto_rawDesc), len(file_proto_tick_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tick_proto_goTypes,
		DependencyIndexes: file_proto_tick_proto_depIdxs,
		MessageInfos:      file_proto_tick_proto_msgTypes,
	}.Build()
	File_proto_tick_proto = out.File
	file_proto_tick_proto_goTypes = nil
	file_proto_tick_proto_depIdxs = nil
}
